### ISSUE TITLE
Couldn't find preset "module:metro-react-native-babel-preset"

### ISSUE THREAD

**Issue by paul019** [rdhox/react-native-smooth-picker#7]
I got this error after running the example code:

<img width="487" alt="bildschirmfoto 2019-01-22 um 18 35 57" src="https://user-images.githubusercontent.com/39464035/51554148-e34c9f80-1e74-11e9-852c-05eff753be46.png">

**Comment by rdhox** [comment]
Sorry I was not able to recreate this bug.
After cloning the repo, did you install the dependencies by doing `yarn` or `npm install` ?

**Comment by paul019** [comment]
I used `npm`...

**Comment by rdhox** [comment]
Work fine for me with `npm`and `yarn`.
There are people complaining about the same issue, fox example:

https://github.com/facebook/react-native/issues/21241
https://github.com/facebook/metro/issues/242
https://stackoverflow.com/questions/54107115/couldnt-find-preset-modulemetro-react-native-babel-preset-relative-to-direct


Seems this issue is not linked to a problem with the picker, I close it.
